# Generated by Django 6.0 on 2025-12-23 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('min_stock_level', models.PositiveIntegerField(default=5, help_text='Alert when stock dips below this')),
                ('rack_location', models.CharField(help_text='e.g., Aisle 3, Shelf B', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty_period_months', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.part')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('make', 'model', 'year')},
            },
        ),
        migrations.AddField(
            model_name='part',
            name='compatible_vehicles',
            field=models.ManyToManyField(blank=True, related_name='compatible_parts', to='inventory.vehicle'),
        ),
    ]
