# Generated by Django 6.0 on 2025-12-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='brand',
            field=models.CharField(blank=True, help_text='e.g., Toyota Genuine, Bosch, K&N', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='part',
            name='rack_location',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.supplier'),
        ),
    ]
