# Generated by Django 6.0 on 2026-01-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_part_brand_alter_part_min_stock_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Optional vehicle reg number', max_length=20, null=True),
        ),
    ]
