# Generated by Django 6.0 on 2026-01-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_vehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='parts/'),
        ),
    ]
