# Generated by Django 6.0 on 2026-01-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_part_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='image_url',
            new_name='image',
        ),
    ]
