# Generated by Django 6.0 on 2026-04-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='rack_location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
