# Generated by Django 6.0 on 2026-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_part_rack_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Reason why this sale was cancelled', null=True),
        ),
    ]
