# Generated by Django 6.0 on 2026-05-22 16:33

from django.db import migrations, models


def migrate_existing_contacts(apps, schema_editor):
    Supplier = apps.get_model('inventory', 'Supplier')
    for supplier in Supplier.objects.all():
        contacts = []
        if supplier.contact_person or supplier.phone:
            contacts.append({
                "name": supplier.contact_person,
                "phones": [supplier.phone] if supplier.phone else []
            })
        supplier.contacts = contacts
        supplier.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_sale_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contacts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(migrate_existing_contacts),
    ]
