# Generated by Django 6.0 on 2026-05-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supplier_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
    ]
