# Generated by Django 6.0 on 2026-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_supplier_contact_person_remove_supplier_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCart',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=20)),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
