# Generated by Django 6.0 on 2026-05-27 15:31

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_employee_phone_employee_phone_numbers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='working_days',
            field=models.JSONField(blank=True, default=inventory.models.default_working_days, help_text='List of working days of the week', null=True),
        ),
    ]
