# Generated by Django 6.0 on 2026-06-25 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_holiday_employee_working_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('buy_price', models.DecimalField(decimal_places=2, help_text='Unit buy price from this supplier for this batch', max_digits=10)),
                ('restocked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_records', to='inventory.part')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_records', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-restocked_at'],
            },
        ),
    ]
