# Generated by Django 6.0 on 2026-07-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_customer_sale_customer_customervehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='color',
            field=models.CharField(blank=True, help_text='e.g., Pearl White', max_length=50),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='current_mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Current odometer reading in km', null=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
