# Generated by Django 6.0 on 2026-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_customervehicle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='credit_note',
            field=models.TextField(blank=True, help_text='Note about the credit sale, e.g. when the customer will pay', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='credit_settled_at',
            field=models.DateTimeField(blank=True, help_text='When this credit sale was marked as received', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('CREDIT', 'Credit (Pay Later)')], default='PAID', max_length=10),
        ),
    ]
