# Generated by Django 6.0 on 2026-07-02 11:12

from django.db import migrations, models


def backfill_amount_paid(apps, schema_editor):
    Sale = apps.get_model('inventory', 'Sale')
    Sale.objects.filter(payment_status='PAID').update(amount_paid=models.F('total_amount'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_sale_credit_note_sale_credit_settled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount actually received at time of sale. Equals total_amount unless payment_status is PARTIAL or CREDIT.', max_digits=12),
        ),
        migrations.RunPython(backfill_amount_paid, noop),
        migrations.AlterField(
            model_name='sale',
            name='credit_note',
            field=models.TextField(blank=True, help_text='Note about the credit/partial sale, e.g. when the customer will pay the balance', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='credit_settled_at',
            field=models.DateTimeField(blank=True, help_text="When this credit/partial sale's balance was marked as received", null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('CREDIT', 'Credit (Pay Later)')], default='PAID', max_length=10),
        ),
    ]
