# Generated by Django 6.0 on 2026-07-16 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_sale_amount_paid_alter_sale_credit_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervehicle',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='inventory.customer'),
        ),
    ]
