# Generated by Django 6.0 on 2026-07-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_customervehicle_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='description',
            field=models.CharField(blank=True, help_text="Used for LABOR items, e.g. 'Brake pad replacement'", max_length=255),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_type',
            field=models.CharField(choices=[('PART', 'Part'), ('LABOR', 'Labor')], default='PART', max_length=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.part'),
        ),
    ]
