# Generated by Django 6.0 on 2026-07-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_saleitem_description_saleitem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecart',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activecart',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text="Vehicle's odometer reading at the time of this job, if known", null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the repair/job performed'),
        ),
    ]
