# Generated by Django 6.0 on 2026-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_activecart_mileage_activecart_notes_sale_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockrecord',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
