# Generated by Django 6.0 on 2026-07-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_restockrecord_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_carts', to='inventory.customer'),
        ),
    ]
