# Generated by Django 6.0 on 2026-07-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_activecart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
