# Generated by Django 6.0 on 2026-08-10 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_supplier_primary_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate_number', models.CharField(blank=True, help_text='Sequential reference, e.g. EST-0001', max_length=20, unique=True)),
                ('vehicle_number', models.CharField(help_text='Plate as printed; kept in sync with the linked vehicle', max_length=20)),
                ('make_model', models.CharField(blank=True, max_length=100)),
                ('insurance_company', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='inventory.customervehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
