# Generated by Django 6.0 on 2026-08-11 12:46

from django.db import migrations, models


def backfill_mileage_recorded_at(apps, schema_editor):
    """
    Date the readings that already exist. A vehicle's current_mileage came from
    the most recent job that recorded one, so use that sale's date; where no
    such sale exists (the reading was typed straight into the registry) fall
    back to the row's last-modified date as the closest thing available.
    """
    CustomerVehicle = apps.get_model('inventory', 'CustomerVehicle')
    Sale = apps.get_model('inventory', 'Sale')

    for vehicle in CustomerVehicle.objects.exclude(current_mileage__isnull=True):
        last_reading = (
            Sale.objects
            .filter(vehicle_number__iexact=vehicle.vehicle_number, mileage__isnull=False)
            .order_by('-created_at')
            .first()
        )
        vehicle.mileage_updated_at = last_reading.created_at if last_reading else vehicle.updated_at
        # update_fields keeps auto_now from bumping updated_at as a side effect.
        vehicle.save(update_fields=['mileage_updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='mileage_updated_at',
            field=models.DateTimeField(blank=True, help_text='When current_mileage was last recorded', null=True),
        ),
        migrations.RunPython(backfill_mileage_recorded_at, migrations.RunPython.noop),
    ]
