# Generated by Django 6.0 on 2026-08-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_customervehicle_mileage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Name the account is held under', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
