# Generated by Django 6.0 on 2026-09-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_alter_sale_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='owner_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estimate',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Plate as printed; kept in sync with the linked vehicle', max_length=20),
        ),
    ]
