# Generated by Django 6.0 on 2026-09-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_estimate_owner_address_estimate_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name_prefix',
            field=models.CharField(blank=True, help_text='Honorific shown before the name, e.g. Mr., Dr., Ven.', max_length=20),
        ),
    ]
