# Generated by Django 6.0 on 2026-09-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_customer_name_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='min_sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lowest price this part may be sold at. Leave blank for no discount limit.', max_digits=10, null=True),
        ),
    ]
