# Generated by Django 6.0 on 2026-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_part_min_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecart',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
