# Generated by Django 6.0 on 2026-09-22 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_activecart_sale_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_number', models.CharField(blank=True, help_text='Sequential reference, e.g. 03795', max_length=20, unique=True)),
                ('inspector_name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_number', models.CharField(blank=True, help_text='Plate as printed; kept in sync with the linked vehicle', max_length=20)),
                ('chassis_number', models.CharField(blank=True, max_length=40)),
                ('make_model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Plug-in Hybrid', 'Plug-in Hybrid'), ('Electric', 'Electric'), ('Other', 'Other')], max_length=20)),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Odometer reading in km at the time of inspection', null=True)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='inspections/')),
                ('rear_image', models.ImageField(blank=True, null=True, upload_to='inspections/')),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('ratings', models.JSONField(blank=True, default=dict)),
                ('system_scan', models.JSONField(blank=True, default=dict)),
                ('dtc_codes', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=dict)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='inventory.customervehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
