# Generated by Django 6.0 on 2026-09-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_vehicleinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='excluded_sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
