# Generated by Django 6.0 on 2026-09-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_vehicleinspection_custom_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Plug-in Hybrid', 'Plug-in Hybrid'), ('Electric', 'Electric'), ('Other', 'Other')], max_length=20),
        ),
    ]
