# Generated by Django 6.0 on 2026-09-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_customervehicle_chassis_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecart',
            name='credit_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activecart',
            name='partial_amount_paid',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='activecart',
            name='payment_mode',
            field=models.CharField(default='PAID', max_length=10),
        ),
    ]
