# Generated by Django 6.0 on 2026-10-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_activecart_credit_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='estimate',
            name='first_registered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='mileage',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='estimate',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
