# Generated by Django 6.0 on 2026-10-07 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_purchase_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='previous_sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='restock_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='inventory.restockrecord'),
        ),
    ]
